UMC-WOWMARKET/WOWMARKET-Server

wow_server/src/main/java/wowmarket/wow_server/domain/BaseEntity.java, wow_server/src/main/java/wowmarket/wow_server/domain/User.java
2023.07.18 User 엔티티 수정 - 모든 컬럼 생성
=> feat: User 엔티티 수정

wow_server/src/main/java/wowmarket/wow_server/domain/Project.java
2023.07.18 project 엔티티에 BLOB를 제외한 컬럼 추가
=> Feat: Project 엔티티 컬럼 추가

src/main/java/wowmarket/wow_server/domain/Demand_detail.java, src/main/java/wowmarket/wow_server/domain/Demand_item.java, src/main/java/wowmarket/wow_server/domain/Demand_project.java
수요조사 프로젝트, 수요조사 상품, 수요조사 주문상세 테이블 생성
연관관계 관련해서 논의 후 수정할 필요 있음
=> [feat]demand entity 생성

src/main/java/wowmarket/wow_server/domain/Order.java, src/main/java/wowmarket/wow_server/domain/Order_detail.java, src/main/java/wowmarket/wow_server/domain/User.java
2023.07.25 Fix: 연관관계, @GeneratedValue strategy 수정
=> Fix: 연관관계, @GeneratedValue strategy 수정

src/main/java/wowmarket/wow_server/domain/Category.java, src/main/java/wowmarket/wow_server/domain/Demand_detail.java, src/main/java/wowmarket/wow_server/domain/Demand_item.java, src/main/java/wowmarket/wow_server/domain/Item.java, src/main/java/wowmarket/wow_server/domain/Notice.java, src/main/java/wowmarket/wow_server/domain/Project.java
strategy identity로 명시
수요조사 관련 도메인 수정에 따른 주석 삭제
=> [fix]strategy 수정 및 주석 삭제 #15

src/main/java/wowmarket/wow_server/domain/BaseEntity.java, src/main/java/wowmarket/wow_server/domain/Role.java, src/main/java/wowmarket/wow_server/domain/User.java, src/main/java/wowmarket/wow_server/global/config/SecurityConfig.java, src/main/java/wowmarket/wow_server/global/jwt/JwtAuthenticationFilter.java, src/main/java/wowmarket/wow_server/global/jwt/JwtTokenProvider.java, src/main/java/wowmarket/wow_server/global/jwt/SecurityUtil.java, src/main/java/wowmarket/wow_server/login/api/UserController.java, src/main/java/wowmarket/wow_server/login/dto/TokenResponseDto.java, src/main/java/wowmarket/wow_server/login/dto/UserSignInRequestDto.java, src/main/java/wowmarket/wow_server/login/dto/UserSignUpRequestDto.java, src/main/java/wowmarket/wow_server/login/service/CustomUserDetailsService.java, src/main/java/wowmarket/wow_server/login/service/UserService.java, src/main/java/wowmarket/wow_server/login/service/UserServiceImpl.java, src/main/java/wowmarket/wow_server/repository/UserRepository.java
BaseEntity에 @EntityListeners(AuditingEntityListener.class) 어노테이션 추가
이메일로 로그인 회원가입 로직 일부 구현 완료하였습니다
=> [feat] 로그인 회원가입 로직 구현 및 BaseEntity 수정

src/main/java/wowmarket/wow_server/mypage/myinfo/controller/MyInfoController.java, src/main/java/wowmarket/wow_server/mypage/myinfo/dto/MyInfoResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myinfo/service/MyInfoService.java, src/main/java/wowmarket/wow_server/repository/UserRepository.java
1. repo
2. do
3. service
4. controller 생성
테스트는 아직. 401 err
=> [Feat] 마이페이지 나의 정보 불러오기 #17

src/main/java/wowmarket/wow_server/domain/User.java, src/main/java/wowmarket/wow_server/mypage/myinfo/controller/MyInfoController.java, src/main/java/wowmarket/wow_server/mypage/myorder/controller/MyOrderController.java, src/main/java/wowmarket/wow_server/mypage/myorder/dto/MyOrderFormListResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myorder/dto/MyOrderFormResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myorder/service/MyOrderService.java, src/main/java/wowmarket/wow_server/repository/OrderDetailRepository.java, src/main/java/wowmarket/wow_server/repository/OrderRepository.java
1. dto
2. service
3. controller 생성 
test는 아직
=> [Feat] 마이페이지-나의 주문폼 전체보기

src/main/java/wowmarket/wow_server/global/config/SecurityConfig.java, src/main/java/wowmarket/wow_server/global/config/WebMvcConfig.java
프론트와의 통신 시 cors 오류 나는 부분 수정했습니다
=> [fix] cors 오류 수정

src/main/java/wowmarket/wow_server/domain/Category.java, src/main/java/wowmarket/wow_server/domain/DemandDetail.java, src/main/java/wowmarket/wow_server/domain/DemandItem.java, src/main/java/wowmarket/wow_server/domain/DemandProject.java, src/main/java/wowmarket/wow_server/domain/Item.java, src/main/java/wowmarket/wow_server/domain/Order.java, src/main/java/wowmarket/wow_server/domain/OrderDetail.java, src/main/java/wowmarket/wow_server/domain/Orders.java, src/main/java/wowmarket/wow_server/domain/Project.java, src/main/java/wowmarket/wow_server/domain/User.java, src/main/java/wowmarket/wow_server/mypage/myorder/controller/MyOrderController.java, src/main/java/wowmarket/wow_server/mypage/myorder/dto/MyOrderFormResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myorder/service/MyOrderService.java, src/main/java/wowmarket/wow_server/repository/OrderDetailRepository.java, src/main/java/wowmarket/wow_server/repository/OrderRepository.java
1. controller 와 service 수정 
2. no property 에러 있었음 노션 문제해결페이지참고
=> [fix]camelcase로 수정 및 마이페이지 나의 주문폼 리스트 반환 #20

src/main/java/wowmarket/wow_server/login/dto/UserSignUpRequestDto.java
회원가입 시 마켓팅 동의 처리 여부 추가했습니다
api명세서를 좀 더 꼼꼼히 보도록 하겠습니다.........
=> [feat]회원가입 시 마켓팅 동의 처리 추가

src/main/java/wowmarket/wow_server/login/service/UserService.java, src/main/java/wowmarket/wow_server/login/service/UserServiceImpl.java
회원가입/로그인 검증 실패 시 400 반환하도록 수정하였습니다
=> [fix] 회원가입/로그인 검증 실패 시 에러 코드 수정

src/main/java/wowmarket/wow_server/domain/OrderDetail.java, src/main/java/wowmarket/wow_server/domain/Orders.java, src/main/java/wowmarket/wow_server/mypage/myorder/controller/MyOrderController.java, src/main/java/wowmarket/wow_server/mypage/myorder/dto/MyOrderFormDetailDto.java, src/main/java/wowmarket/wow_server/mypage/myorder/dto/MyOrderFormDetailResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myorder/service/MyOrderService.java, src/main/java/wowmarket/wow_server/repository/OrderDetailRepository.java
=> [feat]나의 주문폼 상세보기 #20

src/main/java/wowmarket/wow_server/WowServerApplication.java, src/main/java/wowmarket/wow_server/domain/Category.java, src/main/java/wowmarket/wow_server/domain/DemandItem.java, src/main/java/wowmarket/wow_server/domain/DemandProject.java, src/main/java/wowmarket/wow_server/domain/Item.java, src/main/java/wowmarket/wow_server/domain/Project.java, src/main/java/wowmarket/wow_server/register/controller/RegisterController.java, src/main/java/wowmarket/wow_server/register/dto/RegisterDemandProjectDto.java, src/main/java/wowmarket/wow_server/register/dto/RegisterItemDto.java, src/main/java/wowmarket/wow_server/register/dto/RegisterProjectDto.java, src/main/java/wowmarket/wow_server/register/service/RegisterService.java, src/main/java/wowmarket/wow_server/register/service/RegisterServiceImpl.java, src/main/java/wowmarket/wow_server/repository/CategoryRepository.java, src/main/java/wowmarket/wow_server/repository/DemandItemRepository.java, src/main/java/wowmarket/wow_server/repository/DemandProjectRepository.java, src/main/java/wowmarket/wow_server/repository/ItemRepository.java, src/main/java/wowmarket/wow_server/repository/ProjectRepository.java
프로젝트/수요조사 등록 api 구현하였습니다
이미지 등록은 아직 하지못했습니다🥲
#30
=> [feat] 프로젝트/ 수요조사 등록 api 구현

src/main/java/wowmarket/wow_server/domain/Category.java, src/main/java/wowmarket/wow_server/domain/DemandDetail.java, src/main/java/wowmarket/wow_server/domain/DemandItem.java, src/main/java/wowmarket/wow_server/domain/DemandProject.java, src/main/java/wowmarket/wow_server/domain/Item.java, src/main/java/wowmarket/wow_server/domain/OrderDetail.java, src/main/java/wowmarket/wow_server/domain/Orders.java, src/main/java/wowmarket/wow_server/domain/Project.java, src/main/java/wowmarket/wow_server/domain/User.java, src/main/java/wowmarket/wow_server/mypage/myorder/controller/MyOrderController.java, src/main/java/wowmarket/wow_server/mypage/myorder/dto/MyOrderFormDetailResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myorder/dto/MyOrderFormDetailUpdateRequestDto.java, src/main/java/wowmarket/wow_server/mypage/myorder/dto/MyOrderFormItemListRequestDto.java, src/main/java/wowmarket/wow_server/mypage/myorder/service/MyOrderService.java, src/main/java/wowmarket/wow_server/repository/OrderDetailRepository.java
1. domain column 이름 카멜로 수정한거 스네이크로 롤백 
2. 주문폼 수정을 위한 request dto, service 적용
=> [feat]나의 주문폼 수정#20

src/main/java/wowmarket/wow_server/domain/Project.java, src/main/java/wowmarket/wow_server/mypage/myproject/controller/MyProjectController.java, src/main/java/wowmarket/wow_server/mypage/myproject/dto/MySalesFormDetailResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/dto/MySalesFormDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/dto/MySalesFormListResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/dto/MySalesItemDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/service/MyProjectService.java, src/main/java/wowmarket/wow_server/repository/ItemRepository.java, src/main/java/wowmarket/wow_server/repository/ProjectRepository.java
1. 판매 등록폼 리스트 전체보기
2. 판매 등록폼 종료
3. 판매 등록폼 상세보기
=> [Feat] 나의 프로젝트 - 판매 등록폼 관리

src/main/java/wowmarket/wow_server/domain/DemandProject.java, src/main/java/wowmarket/wow_server/domain/Project.java, src/main/java/wowmarket/wow_server/domain/Role.java, src/main/java/wowmarket/wow_server/domain/User.java, src/main/java/wowmarket/wow_server/global/S3Uploader.java, src/main/java/wowmarket/wow_server/global/config/S3Config.java, src/main/java/wowmarket/wow_server/global/config/SecurityConfig.java, src/main/java/wowmarket/wow_server/global/jwt/JwtAuthenticationFilter.java, src/main/java/wowmarket/wow_server/global/jwt/JwtTokenProvider.java, src/main/java/wowmarket/wow_server/login/service/UserServiceImpl.java, src/main/java/wowmarket/wow_server/register/controller/RegisterController.java, src/main/java/wowmarket/wow_server/register/service/RegisterService.java, src/main/java/wowmarket/wow_server/register/service/RegisterServiceImpl.java
프로젝트/ 수요조사 등록 페이지에 aws s3 이용하여 이미지 업로드 구현까지 완료하였습니다.
Closes #30
=> [feat] 이미지 등록 구현

src/main/java/wowmarket/wow_server/domain/Orders.java, src/main/java/wowmarket/wow_server/mypage/myproject/controller/MyProjectController.java, src/main/java/wowmarket/wow_server/mypage/myproject/dto/MySalesOrderDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/dto/MySalesOrderListResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/dto/MySalesOrderStatusRequestDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/service/MyProjectService.java, src/main/java/wowmarket/wow_server/repository/OrderRepository.java, src/main/java/wowmarket/wow_server/repository/ProjectRepository.java
1. 판매 주문폼 전체 보기
2. 판매 주문폼 상태변경
=> [feat] 판매 주문폼 관리 #42

src/main/java/wowmarket/wow_server/mypage/myproject/controller/MyProjectController.java, src/main/java/wowmarket/wow_server/mypage/myproject/dto/MySalesOrderDetailDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/dto/MySalesOrderDetailResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/service/MyProjectService.java
=> [feat] 마이페이지-판매 주문폼 관리

src/main/java/wowmarket/wow_server/domain/Project.java, src/main/java/wowmarket/wow_server/login/dto/TokenResponseDto.java, src/main/java/wowmarket/wow_server/login/service/UserServiceImpl.java, src/main/java/wowmarket/wow_server/register/dto/RegisterDemandProjectDto.java, src/main/java/wowmarket/wow_server/register/dto/RegisterItemDto.java, src/main/java/wowmarket/wow_server/register/dto/RegisterProjectDto.java
- 판매 프로젝트 등록 페이지 와프에 맞게 수정
- 로그인 ResponseBody 수정
=> [fix] 판매 프로젝트 등록 페이지 와프에 맞게 수정

src/main/java/wowmarket/wow_server/domain/DemandItem.java, src/main/java/wowmarket/wow_server/domain/DemandProject.java, src/main/java/wowmarket/wow_server/mypage/myorder/dto/MyOrderFormResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/controller/MyProjectController.java, src/main/java/wowmarket/wow_server/mypage/myproject/dto/MyDemandDetailResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/dto/MyDemandDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/dto/MyDemandItemDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/dto/MyDemandOrderDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/dto/MyDemandOrderResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/dto/MyDemandResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/dto/MySalesDetailResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/dto/MySalesFormDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/dto/MySalesListResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/dto/MySalesOrderDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/service/MyProjectService.java, src/main/java/wowmarket/wow_server/repository/DemandItemRepository.java, src/main/java/wowmarket/wow_server/repository/DemandProjectRepository.java
1. 수요조사 등록폼 리스트
2. 수요조사 등록폼 상태 변경
3. 수요조사 등록폼 상세보기
=> [feat] 마이페이지-수요조사 등록폼 관리

src/main/java/wowmarket/wow_server/global/config/RedisConfig.java, src/main/java/wowmarket/wow_server/global/config/SecurityConfig.java, src/main/java/wowmarket/wow_server/global/jwt/JwtAuthenticationFilter.java, src/main/java/wowmarket/wow_server/global/jwt/JwtTokenProvider.java, src/main/java/wowmarket/wow_server/login/api/UserController.java, src/main/java/wowmarket/wow_server/login/service/UserService.java, src/main/java/wowmarket/wow_server/login/service/UserServiceImpl.java
#49 redis 이용하여 로그아웃 구현하였습니다
jwt 발급 시크릿 키도 application.properties에 숨겼습니다
=> [feat]로그아웃 구현

src/main/java/wowmarket/wow_server/login/service/UserService.java
=> [fix]import 오류 

src/main/java/wowmarket/wow_server/demand/service/DemandHomeService.java, src/main/java/wowmarket/wow_server/demand/service/DemandSearchService.java, src/main/java/wowmarket/wow_server/login/service/KakaoAPIService.java, src/main/java/wowmarket/wow_server/repository/DemandItemRepository.java, src/main/java/wowmarket/wow_server/repository/DemandProjectRepository.java, src/main/java/wowmarket/wow_server/repository/ProjectRepository.java, src/main/java/wowmarket/wow_server/sale/controller/SaleController.java, src/main/java/wowmarket/wow_server/sale/service/SaleHomeService.java, src/main/java/wowmarket/wow_server/sale/service/SaleSearchService.java, src/main/java/wowmarket/wow_server/univ/service/UnivService.java
Reverts UMC-WOWMARKET/WOWMARKET-Server#61
=> Revert "[Fix] 오류 읽어오기 및 예외처리&쿼리 수정 - DB에서 필터링 "

src/main/java/wowmarket/wow_server/domain/Question.java
=> [feat] 문의 엔티티

src/main/java/wowmarket/wow_server/repository/ProjectRepository.java, src/main/java/wowmarket/wow_server/sale/service/SaleHomeService.java, src/main/java/wowmarket/wow_server/sale/service/SaleSearchService.java
2023.08.06 
Revert로 판매 페이지 성능 개선 & 예외 처리 다시 반영
Project 다 가져오지 않고 ProjectRepository에서 필터링 후 가져오기
로그인 O && 학교 인증 X && myUniv 접근 시 401 UNAUTHORIZED 반환
=> [Fix] 판매 페이지 성능개선&예외처리 다시 반영

src/main/java/wowmarket/wow_server/demand/service/DemandHomeService.java, src/main/java/wowmarket/wow_server/demand/service/DemandSearchService.java, src/main/java/wowmarket/wow_server/repository/DemandProjectRepository.java, src/main/java/wowmarket/wow_server/sale/service/SaleHomeService.java, src/main/java/wowmarket/wow_server/sale/service/SaleSearchService.java
2023.08.06
Revert로 수요조사 페이지 성능 개선 & 예외 처리 다시 반영
DemandProject 다 가져오지 않고 DemandProjectRepository에서 DB에서 필터링 후 가져오기
로그인 X || 학교인증 X -> myUniv 접근 시 401 UNAUTHORIZED 반환
=> [Fix] 수요조사 페이지 성능개선 & 예외처리 다시 반영

src/main/java/wowmarket/wow_server/mypage/myinfo/controller/MyInfoController.java, src/main/java/wowmarket/wow_server/mypage/myinfo/dto/MyInfoResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myinfo/service/MyInfoService.java, src/main/java/wowmarket/wow_server/mypage/myorder/controller/MyOrderController.java, src/main/java/wowmarket/wow_server/mypage/myorder/dto/MyOrderFormResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myorder/service/MyOrderService.java
=> [feat]마이페이지-나의 정보, 주문리스트 유저 정보 받아오기로 변경 #68

src/main/java/wowmarket/wow_server/login/service/KakaoAPIService.java, src/main/java/wowmarket/wow_server/repository/ItemRepository.java, src/main/java/wowmarket/wow_server/repository/ProjectRepository.java, src/main/java/wowmarket/wow_server/sale/service/SaleHomeService.java, src/main/java/wowmarket/wow_server/sale/service/SaleSearchService.java, src/main/java/wowmarket/wow_server/univ/service/UnivService.java
2023.08.08
판매 프로젝트 종료여부 및 삭제여부 확인
DB에서 종료여부, 삭제여부, 사용자 학교, 검색 조건 걸러서 가져오기
카카오 api 키 숨김, 에러 읽어오기
학교인증 에러 메세지 추가
=> [Fix] 프로젝트 종료여부 삭제여부 확인

src/main/java/wowmarket/wow_server/demand/service/DemandHomeService.java, src/main/java/wowmarket/wow_server/demand/service/DemandSearchService.java, src/main/java/wowmarket/wow_server/domain/DemandProject.java, src/main/java/wowmarket/wow_server/mypage/myproject/dto/MyDemandDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/mysales/service/MySalesProjectService.java, src/main/java/wowmarket/wow_server/mypage/myproject/service/MyProjectService.java, src/main/java/wowmarket/wow_server/repository/DemandItemRepository.java, src/main/java/wowmarket/wow_server/repository/DemandProjectRepository.java, src/main/java/wowmarket/wow_server/repository/ProjectRepository.java, src/main/java/wowmarket/wow_server/sale/service/SaleSearchService.java
2023.08.08
도메인 컬럼명 변경으로 인한 수정
수요조사 프로젝트 종료여부 및 삭제여부 확인
DB에서 종료여부, 사용자 학교, 검색 조건 걸러서 가져오기
조인 나중에 적용
=> [Fix] 수요조사 프로젝트 종료여부 확인

src/main/java/wowmarket/wow_server/global/config/WebMvcConfig.java
WebMvcConfig 파일 localhost:3002로 변경
=> [feat]proxy 설정 변경

src/main/java/wowmarket/wow_server/global/config/WebMvcConfig.java
=> [feat]허용메소드 수정

src/main/java/wowmarket/wow_server/domain/Project.java, src/main/java/wowmarket/wow_server/login/service/UserServiceImpl.java, src/main/java/wowmarket/wow_server/register/dto/RegisterProjectDto.java, src/main/java/wowmarket/wow_server/register/service/RegisterService.java
- 프로젝트 테이블 receive_type = "delivery" 혹은 "pickup"
-> 픽업일시 address 입력도 받는 것으로 수정 완료
- 400 에러 반환 시 메세지 추가
=> [refactor] 프로젝트테이블에 주소 추가

src/main/java/wowmarket/wow_server/demand/controller/DemandController.java, src/main/java/wowmarket/wow_server/demand/dto/DemandDto.java, src/main/java/wowmarket/wow_server/demand/dto/DemandResponseDto.java, src/main/java/wowmarket/wow_server/demand/service/DemandHomeService.java, src/main/java/wowmarket/wow_server/demand/service/DemandSearchService.java, src/main/java/wowmarket/wow_server/domain/DemandProject.java, src/main/java/wowmarket/wow_server/login/dto/KakaoResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/MyDemandProject/dto/MyDemandDetailResponseDto.java, src/main/java/wowmarket/wow_server/register/dto/RegisterDemandProjectDto.java, src/main/java/wowmarket/wow_server/repository/DemandProjectRepository.java, src/main/java/wowmarket/wow_server/repository/ProjectRepository.java, src/main/java/wowmarket/wow_server/sale/controller/SaleController.java, src/main/java/wowmarket/wow_server/sale/dto/SaleDto.java, src/main/java/wowmarket/wow_server/sale/dto/SaleResponseDto.java, src/main/java/wowmarket/wow_server/sale/service/SaleHomeService.java, src/main/java/wowmarket/wow_server/sale/service/SaleSearchService.java
2023.08.11
1. DemandProject 도메인 컬럼명 변경
end_date, start_date -> endDate, startDate
이에 따른 getter 변경
2. 수요조사 페이지 List -> Page로 변경
3. 썸네일 이미지 반환 적용
=> [Feat] 페이지네이션 적용

src/main/java/wowmarket/wow_server/mypage/myorder/controller/MyOrderController.java, src/main/java/wowmarket/wow_server/mypage/myorder/dto/MyOrderFormDetailResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myorder/dto/MyOrderFormResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myorder/service/MyOrderService.java, src/main/java/wowmarket/wow_server/mypage/myproject/MyDemandProject/dto/MyDemandDetailResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/MyDemandProject/dto/MyDemandDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/MyDemandProject/dto/MyDemandItemDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/MyDemandProject/service/MyDemandProjectService.java, src/main/java/wowmarket/wow_server/mypage/myproject/MySalesOrder/dto/MySalesOrderDetailDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/MySalesOrder/dto/MySalesOrderDetailResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/MySalesOrder/dto/MySalesOrderDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/MySalesOrder/service/MySalesOrderService.java, src/main/java/wowmarket/wow_server/mypage/myproject/MySalesProject/controller/MySalesProjectController.java, src/main/java/wowmarket/wow_server/mypage/myproject/MySalesProject/dto/MySalesDetailResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/MySalesProject/dto/MySalesFormDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/MySalesProject/dto/MySalesItemDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/MySalesProject/service/MySalesProjectService.java
1. thumbnail, image 컬럼 추가
2. address_detail 삭제
3. service 에서 void -> responseEntity 반환으로 변경
=> [feat] 마이페이지-thumbnail, img 추가 및 return 값 변경 #77

src/main/java/wowmarket/wow_server/domain/DemandProject.java, src/main/java/wowmarket/wow_server/domain/Project.java, src/main/java/wowmarket/wow_server/global/S3Uploader.java, src/main/java/wowmarket/wow_server/login/api/UserController.java, src/main/java/wowmarket/wow_server/login/service/UserService.java, src/main/java/wowmarket/wow_server/login/service/UserServiceImpl.java, src/main/java/wowmarket/wow_server/register/controller/RegisterController.java, src/main/java/wowmarket/wow_server/register/dto/RegisterDemandProjectDto.java, src/main/java/wowmarket/wow_server/register/dto/RegisterProjectDto.java, src/main/java/wowmarket/wow_server/register/service/RegisterService.java
=> [feat] @AuthenticationPrincipal로 유저정보 받아오기

src/main/java/wowmarket/wow_server/global/config/WebMvcConfig.java
=> [fix] cors 에러 해결 시도

src/main/java/wowmarket/wow_server/detail/project/controller/ProjectController.java, src/main/java/wowmarket/wow_server/detail/project/dto/ProjectImgResponseDto.java, src/main/java/wowmarket/wow_server/detail/project/dto/ProjectInfoResponseDto.java, src/main/java/wowmarket/wow_server/detail/project/service/ProjectService.java, src/main/java/wowmarket/wow_server/domain/Project.java, src/main/java/wowmarket/wow_server/repository/ProjectRepository.java
- 프로젝트 상세 정보 조회
- 굿즈 소개(이미지) 3개 조회
=> [feat] 프로젝트 상세 정보 조회(조회수 증가 로직 포함) & 굿즈 소개 이미지 조회 api

src/main/java/wowmarket/wow_server/detail/demandproject/controller/DemandProjectController.java, src/main/java/wowmarket/wow_server/detail/demandproject/dto/DemandItemResponseDto.java, src/main/java/wowmarket/wow_server/detail/demandproject/dto/DemandProjectImgResponseDto.java, src/main/java/wowmarket/wow_server/detail/demandproject/dto/DemandProjectInfoResponseDto.java, src/main/java/wowmarket/wow_server/detail/demandproject/service/DemandItemService.java, src/main/java/wowmarket/wow_server/detail/demandproject/service/DemandProjectService.java, src/main/java/wowmarket/wow_server/detail/project/controller/ProjectController.java, src/main/java/wowmarket/wow_server/detail/project/dto/ItemResponseDto.java, src/main/java/wowmarket/wow_server/detail/project/service/ItemService.java, src/main/java/wowmarket/wow_server/detail/project/service/ProjectService.java, src/main/java/wowmarket/wow_server/domain/DemandProject.java, src/main/java/wowmarket/wow_server/domain/Project.java, src/main/java/wowmarket/wow_server/repository/DemandProjectRepository.java
[feat]
1. 주문폼 (project)
- 상세 정보(좌측 상단) 불러오기
- 굿즈소개(이미지 3개) 불러오기
- 상품 정보(우측) 불러오기 
2. 참여폼 (=수요조사폼) (demandProject)
- 상세 정보(좌측 상단) 불러오기
- 굿즈소개(이미지 3개) 불러오기
- 상품 정보(우측) 불러오기 
[fix]
- 재진행 컬럼 삭제
=> [feat/fix] 주문폼&참여폼 [상세 정보, 굿즈소개(이미지), 상품 정보] 불러오기 api / 재진행 컬럼 삭제

src/main/java/wowmarket/wow_server/mypage/myinfo/controller/MyInfoController.java, src/main/java/wowmarket/wow_server/mypage/myinfo/service/MyInfoService.java, src/main/java/wowmarket/wow_server/mypage/myorder/controller/MyOrderController.java, src/main/java/wowmarket/wow_server/mypage/myorder/service/MyOrderService.java, src/main/java/wowmarket/wow_server/mypage/myproject/MyDemandProject/controller/MyDemandProjectController.java, src/main/java/wowmarket/wow_server/mypage/myproject/MyDemandProject/service/MyDemandProjectService.java, src/main/java/wowmarket/wow_server/mypage/myproject/MySalesOrder/controller/MySalesOrderController.java, src/main/java/wowmarket/wow_server/mypage/myproject/MySalesOrder/service/MySalesOrderService.java, src/main/java/wowmarket/wow_server/mypage/myproject/MySalesProject/controller/MySalesProjectController.java, src/main/java/wowmarket/wow_server/mypage/myproject/MySalesProject/service/MySalesProjectService.java
1. 어노테이션 사용해서 로그인한 사용자 정보 받아오기로 수정
2. url에서 wowmarket 전부 삭제
3. 나의 정보에 myinfo 붙임
=> [feat] url 수정 및 로그인 정보 받아오기 수정

src/main/java/wowmarket/wow_server/domain/Project.java, src/main/java/wowmarket/wow_server/global/config/SecurityConfig.java, src/main/java/wowmarket/wow_server/register/dto/RegisterProjectDto.java
=> [feat] 배송비 추가

src/main/java/wowmarket/wow_server/terms/controller/TermsController.java
=> [feat]이용약관, 개인정보처리방침

src/main/java/wowmarket/wow_server/domain/DemandDetail.java, src/main/java/wowmarket/wow_server/domain/DemandItem.java, src/main/java/wowmarket/wow_server/domain/Item.java, src/main/java/wowmarket/wow_server/domain/OrderDetail.java
=> [feat]default값 설정

src/main/java/wowmarket/wow_server/domain/User.java
=> [feat] boolean default 변경

src/main/java/wowmarket/wow_server/register/dto/RegisterDemandProjectDto.java, src/main/java/wowmarket/wow_server/register/dto/RegisterProjectDto.java, src/main/java/wowmarket/wow_server/register/service/RegisterService.java
- @NotNull 애노테이션 추가
- 프로젝트 등록 시 유저 찾을 수 없을 때 400 반환하도록 수정
=> [refactor] @NotNull 애노테이션 추가

src/main/java/wowmarket/wow_server/global/config/SecurityConfig.java
=> [feat]프론트 url 변경으로 open추가

src/main/java/wowmarket/wow_server/mypage/myproject/MyDemandProject/dto/MyDemandDto.java
=> [feat]수요조사 전체보기에서 isend->status로 명칭 변경

src/main/java/wowmarket/wow_server/demand/service/DemandHomeService.java, src/main/java/wowmarket/wow_server/demand/service/DemandSearchService.java, src/main/java/wowmarket/wow_server/repository/DemandProjectRepository.java, src/main/java/wowmarket/wow_server/repository/ProjectRepository.java, src/main/java/wowmarket/wow_server/sale/controller/SaleController.java, src/main/java/wowmarket/wow_server/sale/service/SaleHomeService.java, src/main/java/wowmarket/wow_server/sale/service/SaleSearchService.java
2023.08.21
1. 리퀘스트 파람 프론트 오타 확인
2. 쿼리 수정 : startDate와 endDate 반영
=> [feat] 프로젝트 기간 반영

src/main/java/wowmarket/wow_server/mypage/myorder/dto/MyOrderFormDetailResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myorder/service/MyOrderService.java, src/main/java/wowmarket/wow_server/mypage/myproject/MySalesOrder/dto/MySalesOrderDetailResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/MySalesOrder/service/MySalesOrderService.java
=> [feat]택배비와 수령장소 수정

src/main/java/wowmarket/wow_server/demand/dto/DemandDto.java, src/main/java/wowmarket/wow_server/detail/demandproject/dto/DemandProjectInfoResponseDto.java, src/main/java/wowmarket/wow_server/detail/project/dto/OrderResponseDto.java, src/main/java/wowmarket/wow_server/detail/project/dto/ProjectInfoResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myorder/dto/MyOrderFormDetailResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myorder/dto/MyOrderFormResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/MyDemandProject/dto/MyDemandDetailResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/MyDemandProject/dto/MyDemandDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/MySalesOrder/dto/MySalesOrderDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/MySalesProject/dto/MySalesDetailResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/MySalesProject/dto/MySalesFormDto.java, src/main/java/wowmarket/wow_server/repository/DemandProjectRepository.java, src/main/java/wowmarket/wow_server/repository/ProjectRepository.java, src/main/java/wowmarket/wow_server/sale/dto/SaleDto.java
projectName 변경 완료
db 스키마 drop 하고 다시 생성하기
=> [feat]projectName 변경 반영

src/main/java/wowmarket/wow_server/detail/project/controller/ProjectController.java, src/main/java/wowmarket/wow_server/detail/project/dto/ProjectInfoResponseDto.java, src/main/java/wowmarket/wow_server/detail/project/service/ProjectService.java
2023.12.29
1. `Like` API 수정
* `like`와 `unlike`에 대해 같은 API 이용
* `like` 상태이면 → `unlike`로, 
* `unlike` 상태이면 `like` 상태로 변경
2. 프로젝트 조회 시 `like` 여부 반영
=> [Feat] Like API 수정 및 프로젝트 조회 수정 #134

src/main/java/wowmarket/wow_server/mypage/myorder/dto/MyOrderFormDetailDto.java, src/main/java/wowmarket/wow_server/mypage/myorder/dto/MyOrderFormDetailResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/MySalesOrder/controller/MySalesOrderController.java, src/main/java/wowmarket/wow_server/mypage/myproject/MySalesOrder/dto/MySalesOrderDetailDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/MySalesOrder/dto/MySalesOrderDetailResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/MySalesOrder/dto/MySalesOrderDto.java
=> [feat] 판매 주문폼, 등록폼, 수집폼 수정

src/main/java/wowmarket/wow_server/detail/demandproject/controller/DemandProjectController.java, src/main/java/wowmarket/wow_server/detail/demandproject/dto/DemandProjectInfoResponseDto.java, src/main/java/wowmarket/wow_server/detail/demandproject/service/DemandProjectService.java, src/main/java/wowmarket/wow_server/domain/DemandLikes.java, src/main/java/wowmarket/wow_server/domain/DemandProject.java, src/main/java/wowmarket/wow_server/repository/DemandLikesRepository.java, src/main/java/wowmarket/wow_server/repository/DemandProjectRepository.java, src/main/java/wowmarket/wow_server/repository/UserRepository.java
2023.12.31
1. 수요조사 Like 기능 API 추가
2. 수요조사 조회 DTO 수정
=> [Feat] 수요조사 Like 기능 #134

src/main/java/wowmarket/wow_server/domain/OrderAnswer.java, src/main/java/wowmarket/wow_server/domain/OrderQuestion.java, src/main/java/wowmarket/wow_server/domain/ReceiveType.java, src/main/java/wowmarket/wow_server/register/dto/RegisterProjectDto.java, src/main/java/wowmarket/wow_server/register/dto/RegisterQuestionDto.java, src/main/java/wowmarket/wow_server/register/service/RegisterService.java, src/main/java/wowmarket/wow_server/repository/OrderAnswerRepository.java, src/main/java/wowmarket/wow_server/repository/OrderQuestionRepository.java
판매자가 프로젝트 등록 시 개별 질문을 제한 없이 할 수 있도록 추가 구현하였습니다
=> [Feat] 프로젝트 등록 시 개별질문 등록 구현

src/main/java/wowmarket/wow_server/mypage/myproject/MyDemandProject/controller/MyDemandProjectController.java, src/main/java/wowmarket/wow_server/mypage/myproject/MyDemandProject/service/MyDemandProjectService.java
=> [feat] 수요조사 등록폼 상세보기 접근 권한 설정 #137

src/main/java/wowmarket/wow_server/converter/ReceiveTypeConverter.java, src/main/java/wowmarket/wow_server/domain/Category.java, src/main/java/wowmarket/wow_server/domain/Item.java, src/main/java/wowmarket/wow_server/domain/Project.java, src/main/java/wowmarket/wow_server/domain/ReceiveType.java, src/main/java/wowmarket/wow_server/mypage/myorder/sales/controller/MyOrderSalesController.java, src/main/java/wowmarket/wow_server/mypage/myorder/sales/service/MyOrderSalesService.java, src/main/java/wowmarket/wow_server/mypage/myproject/MySalesOrder/service/MySalesOrderService.java, src/main/java/wowmarket/wow_server/mypage/myproject/MySalesProject/controller/MySalesProjectController.java, src/main/java/wowmarket/wow_server/mypage/myproject/MySalesProject/dto/MySalesItemDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/MySalesProject/dto/MySalesProjectModifyRequestDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/MySalesProject/service/MySalesProjectService.java
=> [feat] 판매 등록폼 수정 #137

src/main/java/wowmarket/wow_server/admin/adminAccount/controller/AdminAccountManagementController.java, src/main/java/wowmarket/wow_server/admin/adminAccount/dto/ChangeRoleRequestDto.java, src/main/java/wowmarket/wow_server/admin/adminAccount/service/AdminAccountManagementService.java, src/main/java/wowmarket/wow_server/domain/DemandItem.java, src/main/java/wowmarket/wow_server/domain/DemandProject.java, src/main/java/wowmarket/wow_server/domain/Role.java, src/main/java/wowmarket/wow_server/domain/User.java, src/main/java/wowmarket/wow_server/mypage/myproject/MyDemandProject/controller/MyDemandProjectController.java, src/main/java/wowmarket/wow_server/mypage/myproject/MyDemandProject/dto/MyDemandProjectModifyRequestDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/MyDemandProject/service/MyDemandProjectService.java, src/main/java/wowmarket/wow_server/mypage/myproject/MySalesProject/dto/MySalesDetailResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/MySalesProject/dto/MySalesProjectModifyRequestDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/MySalesProject/service/MySalesProjectService.java
1. 수요조사 등록폼 수정 기능 구현
2. 배송 방법 이름 or 수령 장소 나타내는 receiveAddress 추가
3. 유저 <-> 관리자 권한 변경
=> [feat] 수요조사 등록폼 수정, 등록폼 receiveAddress 추가, 유저 role 변경

src/main/java/wowmarket/wow_server/admin/adminAccount/controller/AdminAccountManagementController.java, src/main/java/wowmarket/wow_server/admin/adminAccount/dto/AdminDto.java, src/main/java/wowmarket/wow_server/admin/adminAccount/dto/AdminResponseDto.java, src/main/java/wowmarket/wow_server/admin/adminAccount/service/AdminAccountManagementService.java, src/main/java/wowmarket/wow_server/mypage/myproject/MySalesProject/controller/MySalesProjectController.java, src/main/java/wowmarket/wow_server/mypage/myproject/MySalesProject/service/MySalesProjectService.java, src/main/java/wowmarket/wow_server/repository/UserRepository.java
1. 관리자 계정 관리 페이지 구현
2. 나의 판매 등록폼 상세보기 판매자만 접근 가능하도록 설정
=> [feat] 관리자 계정 관리, 나의 판매 등록폼 상세보기 권한 설정

src/main/java/wowmarket/wow_server/mypage/myproject/MyDemandProject/controller/MyDemandProjectController.java, src/main/java/wowmarket/wow_server/mypage/myproject/MyDemandProject/dto/DemandAddtionalQuestionDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/MyDemandProject/dto/MyDemandDetailResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/MyDemandProject/service/MyDemandProjectService.java, src/main/java/wowmarket/wow_server/mypage/myproject/MySalesProject/dto/MySalesDetailResponseDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/MySalesProject/dto/SalesAdditionalQuestionDto.java, src/main/java/wowmarket/wow_server/mypage/myproject/MySalesProject/service/MySalesProjectService.java, src/main/java/wowmarket/wow_server/repository/DemandQuestionRepository.java
1. 판매 등록폼 상세보기에서 추가 질문 구현
2. 수요조사 등록폼 상세보기에서 추가 질문 구현
=> [feat] 등록폼 관리 추가 질문
